# SPDX-License-Identifier: GPL-3.0-or-later
# Originally generated by nixos-generate-config, hand-maintained since.
#
# The old "do not edit manually" header was already false: this file carries an
# SPDX identifier that generate-config does not emit and Standard §4 requires,
# its mode was normalized in 0cc2a45, and it was adapted rather than regenerated
# when hosts/ was split per machine in e797128.
#
# So regenerating is ALREADY a reconcile-by-hand operation, not a redirect:
# re-add the SPDX line, then `nix fmt`. Overwriting this file wholesale drops
# the licence header.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/667c95b9-16ac-449a-b36c-7a4e156620c3";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/30F4-BB7D";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
